#!/bin/bash

# ----[ STRICT MODE ]----
set -e
set -u
set -o pipefail
TARGET=$1
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
REPO_DIR=$(realpath ${SCRIPT_DIR}/../..)
BUILD_DIR=${REPO_DIR}/build_${TARGET}

mkdir -p ${BUILD_DIR} 
cd ${BUILD_DIR}
${REPO_DIR}/configure --target-list=${TARGET} --disable-werror
ninja 
