#!/bin/bash

# ----[ STRICT MODE ]----
set -e
set -u
set -o pipefail
TARGET_LIST="riscv64cheri-softmmu,riscv32cheri-softmmu"
NINJA_TARGETS="qemu-system-riscv64cheri qemu-system-riscv32cheri"
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
REPO_DIR=$(realpath ${SCRIPT_DIR}/../..)
BUILD_DIR=${REPO_DIR}/build

QEMU_CONFIG="--disable-gtk \
    --audio-drv-list="" \
    --disable-brlapi \
    --disable-libiscsi \
    --disable-libnfs \
    --disable-rbd \
    --disable-sdl \
    --disable-snappy \
    --disable-vnc \
    --disable-vnc-jpeg \
    --disable-vnc-sasl \
    --disable-werror \
    --prefix=$1"

mkdir -p ${BUILD_DIR} 
cd ${BUILD_DIR}
${REPO_DIR}/configure --target-list=${TARGET_LIST} ${QEMU_CONFIG}
ninja ${NINJA_TARGETS} && ./${NINJA_TARGET} --version
ninja install
