# This script only works under the prerequisite of a completed yocto build for the 
# specified machine, with the yocto directory set in the corresponding variable.
# The latest commit at the time of development was 2d8264c16a1bd0c942bc147558c68e40d353796a. 

yocto_path="../../../yocto3/build"
machine="2-vcu118"
imagepath=$yocto_path/tmp/deploy/images/hobgoblin$machine

# resize image for gitlab-public yocto build
qemu-img resize -f raw ${imagepath}/core-image-minimal-hobgoblin$machine.sdcard.wic 256M

qemu-system-riscv64cheri  \
-m 1G -smp cpus=4,cores=4,threads=1,sockets=1 \
-machine hobgoblin-v$machine  \
-bios ${imagepath}/fw_dynamic.bin  \
-kernel ${imagepath}/Image  \
-drive file=${imagepath}/core-image-minimal-hobgoblin$machine.sdcard.wic,if=sd   \
-append "root=/dev/mmcblk0p2 console=ttyS0"  \
-serial mon:stdio  \
-dtb qemu-system-riscv64cheri-v$machine-smp4.dtb

# This is the devicetree dumped by qemu
# -dtb qemu-system-riscv64cheri-v$machine.dtb

# This is the devicetree generated by yocto
# -dtb ${imagepath}/x730-mp1-hobgoblin$machine-qemu-hobgoblin$machine.dtb \